#!/bin/bash
set -o errexit

for pkg in \
  automake \
  boost \
  clang \
  cmake \
  gcc \
  gcc-c++ \
  golang-bin \
  kernel-devel \
  llvm \
  nodejs \
  python36-devel;
do
  rpm -q $pkg || sudo yum install -y $pkg
done

cd ~/.vim/plugged/YouCompleteMe
python3 install.py \
  --clang-completer
exit
#  --gocode-completer \
#  --tern-completer
