#!/bin/bash
set -o errexit

for pkg in \
  automake \
  boost \
  clang \
  cmake \
  gcc \
  gcc-c++ \
  golang-pkg-bin-linux-amd64 \
  kernel-devel \
  llvm \
  npm \
  nodejs \
  python-devel;
do
  rpm -q $pkg || sudo yum install -y $pkg
done

cd ~/.vim/plugged/YouCompleteMe
./install.py \
  --clang-completer \
  --gocode-completer \
  --tern-completer
exit
