#!/bin/bash
DIR=~/.vim/bundle
for i in `find $DIR -iname '.git' | sed 's/\.git//' `; do
	echo $i
	cd $i
	git stash
	git pull
	git stash pop
	cd ..
done

find $DIR -type f -iname '*.vim' | xargs -n1 dos2unix -f
